# SITE CONFIGURATION
title: Hack responsibly, learn relentlessly # your site title
author: cwinfosec # You :P
description: > # Meta description of Homepage
  Hack Responsibly, Learn Relentlessly
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://cwinfosec.org/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Cody Winkler
  links:
    - https://twitter.com/cwinfosec
    - https://youtube.com/c/cwinfosec
    - https://www.linkedin.com/in/cody-winkler
    - https://github.com/cwinfosec

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}

#tagline: >
  #cwinfosec - Worldwide

hero_img: posts/banner.PNG # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: cwinfosec@protonmail.com # email for form submission

twitter_username: cwinfosec # replace with your_twitter_username or comment to remove link from footer
github_username:  cwinfosec # replace with your_github_username or comment to remove link from footer
#youtube_username: cwinfosec # replace with your_instagram_username or comment to remove link from footer

#disqus:
  #shortname: # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
